name: flowdock-rest
version: 0.2.0.0
synopsis: Flowdock REST API
description: |
  Bindings to the <https://www.flowdock.com/api/rest Flowdock REST API>.

  Currently there are only non-destructive operations.
  Also not all types are written out.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-flowdock-rest
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.2, GHC==8.2.1
extra-source-files:
- README.md
- fixtures/*.json

ghc-options: -Wall

dependencies:
  - base                  >=4.7   && <4.11
  - base-compat           >=0.6   && <0.10
  - aeson                 >=0.8   && <1.3
  - aeson-compat          >=0.3.4.0 && <0.4
  - ansi-pretty           >=0.1   && <0.2
  - binary-orphans        >=0.1.1 && <0.2
  - binary-tagged         >=0.1.1 && <0.2
  - bytestring            >=0.10  && <0.11
  - cassava               >=0.4.5.0 && <0.6
  - deepseq               >=1.3   && <1.5
  - exceptions            >=0.8   && <0.9
  - generics-sop          >=0.1   && <0.4
  - hashable              >=1.2   && <1.3
  - lucid                 >=2.9.6 && <2.10
  - http-client           >=0.4.30 && <0.6
  - lens                  >=4.7   && <4.16
  - semigroups            >=0.16  && <0.19
  - tagged                >=0.7   && <0.9
  - time                  >=1.4   && <1.9
  - transformers          >=0.3   && <0.6
  - text                  >=1.2   && <1.3
  - vector                >=0.10  && <0.13

library:
  source-dirs: src

tests:
  flowdock-rest-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - flowdock-rest
      - tasty                 >=0.10  && <0.12
      - tasty-quickcheck      >=0.8   && <0.10
      - file-embed            >=0.0.9
